#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}



#-------------------------------
# Contact Section

social:

- {icon: 'github',    link: 'https://flaviagdo.github.io/html-site/'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/fl%C3%A1via-de-oliveira-1953b4134/'}

